
### get all houses
GET http://localhost:2403/v1/houses?userId=9b3fe93d-22e4-4e91-a354-b677b7bc6186

### publish house
POST http://localhost:2403/v1/houses?userId=9b3fe93d-22e4-4e91-a354-b677b7bc6186
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="lat"

6.2442
--WebAppBoundary
Content-Disposition: form-data; name="lng"

-75.5812
--WebAppBoundary
Content-Disposition: form-data; name="description"

Casa en la Estrella pero me parece muy escondida
--WebAppBoundary
Content-Disposition: form-data; name="phone"

+573001234567
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="casa.jpg"
Content-Type: image/jpeg

< ./casa.jpg
--WebAppBoundary--

### unpublish house
DELETE http://localhost:2403/v1/houses/11812c7c-ac53-4a3b-80a6-db417063da38?userId=9b3fe93d-22e4-4e91-a354-b677b7bc6186&reason=No me gusta

### mark house as interested
POST http://localhost:2403/v1/houses/11812c7c-ac53-4a3b-80a6-db417063da38/interest?userId=9b3fe93d-22e4-4e91-a354-b677b7bc6186
